apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sum-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-sum-app
  template:
    metadata:
      labels:
        app: flask-sum-app
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: flask-sum-app
        image: fullstackmalinda/flask_sum_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-sum-app-service
spec:
  type: NodePort
  selector:
    app: flask-sum-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
